name: yaaseen
description: Yasin sura.

version: 2.2.3+16

environment:
  sdk: ">=2.18.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  flutter_screenutil: ^5.5.3+2
  flutter_bloc: ^8.1.1
  share_plus: ^6.2.0
  audioplayers: ^1.0.1
  url_launcher: ^6.1.5
  flutter_svg: ^1.0.3
  in_app_review: ^2.0.4
  http: ^0.13.5
  firebase_core: ^2.1.1
  firebase_messaging: ^14.0.4
  firebase_auth: ^4.1.1
  cloud_firestore: ^4.0.4
  flutter_local_notifications: ^12.0.3
  uuid: ^3.0.6
  package_info_plus: ^3.0.1
  audio_service: ^0.18.7
  just_audio: ^0.9.29
  firebase_database: ^10.0.4
  flutter_html: ^3.0.0-alpha.3
  firebase_analytics: ^10.0.4
  badges: ^2.0.3
  on_click: ^1.1.3
  connectivity_plus: ^3.0.2
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  integration_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  build_runner: ^2.2.0


flutter:


  uses-material-design: true

  assets:
    - assets/audio/
    - assets/icons/


  fonts:
    - family: Me-Quran
      fonts:
        - asset: assets/fonts/arabic/Me-Quran-Regular.ttf
    
    - family: Al-Qalam
      fonts:
        - asset: assets/fonts/arabic/al-qalam-kitab.ttf

    - family: Amiri
      fonts:
        - asset: assets/fonts/arabic/Amiri-Bold.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700


